name: Create Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install Dependecies
        run: npm ci
      - name: Run the tests
        run: |
          CI=true npm test
        env:
          CI: true
      - name: Build project assets
        run: npm run build
  release:
    name: Release project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
