# Generated by Django 4.1.6 on 2023-05-04 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("host", "0002_remove_host_players_playerjoining"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerJoining",
            new_name="PlayerRoom",
        ),
    ]
