# Generated by Django 4.1.6 on 2023-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0003_rename_playerjoining_playerroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="max_players",
            field=models.SmallIntegerField(default=7),
        ),
    ]
