# Generated by Django 4.1.6 on 2023-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0004_host_max_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="ip",
            field=models.GenericIPAddressField(default="127.0.0.1"),
        ),
        migrations.AddField(
            model_name="host",
            name="port",
            field=models.PositiveSmallIntegerField(default=8080),
        ),
        migrations.AlterField(
            model_name="host",
            name="max_players",
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
