# Generated by Django 4.1.6 on 2023-05-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0011_alter_host_room_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="host",
            old_name="room_status",
            new_name="status",
        ),
    ]
