# Generated by Django 4.1.6 on 2023-05-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0013_userhost_delete_userroom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="host",
            options={},
        ),
    ]
