# Generated by Django 4.1.6 on 2023-04-11 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colour", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("unit_spawn", models.BooleanField(default=False)),
                ("is_sea", models.BooleanField(default=False)),
                ("is_coast", models.BooleanField(default=False)),
                ("text_pos", models.CharField(max_length=10)),
                ("abbreviation", models.CharField(max_length=3)),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="room.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("max_countries", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Maps",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instruction",
                    models.CharField(
                        choices=[
                            ("HLD", "Hold"),
                            ("MVE", "Move"),
                            ("SPT", "Support"),
                            ("CVY", "Convoy"),
                        ],
                        default="HLD",
                        max_length=3,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_location",
                        to="room.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("is_autumn", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_float", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.location"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Units",
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validation", models.BooleanField()),
                (
                    "order_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="order_reference",
                        to="room.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Outcomes",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="reference_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reference_unit",
                to="room.unit",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reference_unit_current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reference_unit_current_location",
                to="room.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reference_unit_new_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reference_unit_new_location",
                to="room.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="target_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="target_location",
                to="room.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="target_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="target_unit",
                to="room.unit",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="room.turn"
            ),
        ),
        migrations.CreateModel(
            name="Next_to",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="room.location",
                    ),
                ),
                (
                    "next_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="next_to",
                        to="room.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Next_to",
            },
        ),
        migrations.CreateModel(
            name="Map_Polygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("polygon", models.CharField(max_length=500)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.location"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Map_Polygons",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.map"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.map"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="player",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
