# Generated by Django 4.1.7 on 2023-03-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('unit_spawn', models.BooleanField()),
                ('is_sea', models.BooleanField()),
                ('is_coast', models.BooleanField()),
                ('polygon', models.CharField(max_length=200)),
                ('text_pos', models.CharField(max_length=10)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.country')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_countries', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Maps',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_autumn', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_float', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.country')),
            ],
            options={
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(choices=[('HLD', 'Hold'), ('MVE', 'Move'), ('SPT', 'Support'), ('CVY', 'Convoy')], default='HLD', max_length=3)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_location', to='room.location')),
                ('reference_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_unit', to='room.unit')),
                ('reference_unit_current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_unit_current_location', to='room.location')),
                ('reference_unit_new_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_unit_new_location', to='room.location')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_location', to='room.location')),
                ('target_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_unit', to='room.unit')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.turn')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Next_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='room.location')),
                ('next_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_to', to='room.location')),
            ],
            options={
                'verbose_name_plural': 'Next_to',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.map'),
        ),
        migrations.AddField(
            model_name='country',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.map'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Outcomes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('room.order',),
        ),
    ]
