# Generated by Django 4.1.6 on 2023-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='text_pos_x',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='text_pos_y',
            field=models.IntegerField(max_length=4),
        ),
    ]
