# Generated by Django 4.1.6 on 2023-05-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="units",
        ),
        migrations.RemoveField(
            model_name="room",
            name="players",
        ),
    ]
