# Generated by Django 4.1.6 on 2023-03-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation', models.BooleanField()),
                ('order_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_reference', to='room.order')),
            ],
            options={
                'verbose_name_plural': 'Outcomes',
            },
        ),
    ]
