# Generated by Django 4.1.6 on 2023-03-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_delete_outcome_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_location', to='room.location'),
        ),
    ]
