# Generated by Django 4.1.6 on 2023-02-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_location_units"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="units",
            options={"verbose_name_plural": "units"},
        ),
    ]
