# Generated by Django 4.1.6 on 2023-03-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_alter_order_reference_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="target_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="target_location",
                to="room.location",
            ),
        ),
    ]
