# Generated by Django 4.1.6 on 2023-02-17 17:37

from django.db import migrations

def initalise_defaults(apps, schema_editor):
    # import the default values for the schema
    Map = apps.get_model('room','Map')
    #only edit current ones??

class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_country_location_map_unit_order_next_to_location_map_and_more'),
    ]

    operations = [
        migrations.RunPython(initalise_defaults),
    ]
