# Generated by Django 4.1.6 on 2023-04-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_location_text_pos_x_alter_location_text_pos_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_polygon',
            name='is_path',
            field=models.BooleanField(default=False),
        ),
    ]
