# Generated by Django 4.1.6 on 2023-04-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_map_polygon_is_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_polygon',
            name='is_path',
        ),
    ]
