# Generated by Django 4.1.6 on 2023-05-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=6)),
                ("build_time", models.DateTimeField(auto_now_add=True)),
                ("close_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_turn",
                        to="room.turn",
                    ),
                ),
            ],
        ),
    ]
