FROM python:3.10-buster

ENV PYTHONBUFFERED 1

WORKDIR /
#home/runner/work/ESRS-diplomacy/ESRS-diplomacy/backend/hostproject/

COPY /home/runner/work/ESRS-diplomacy/ESRS-diplomacy/backend/hostproject/requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

CMD gunicorn backend.wsgi:application --bind 0.0.0.0:8000

EXPOSE 8000