# Generated by Django 4.1.6 on 2023-05-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("colour", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("unit_spawn", models.BooleanField(default=False)),
                ("is_sea", models.BooleanField(default=False)),
                ("is_coast", models.BooleanField(default=False)),
                ("text_pos_x", models.IntegerField(default=0)),
                ("text_pos_y", models.IntegerField(default=0)),
                ("abbreviation", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("max_countries", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Maps",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instruction",
                    models.CharField(
                        choices=[
                            ("HLD", "Hold"),
                            ("MVE", "Move"),
                            ("SPT", "Support"),
                            ("CVY", "Convoy"),
                        ],
                        default="HLD",
                        max_length=3,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_location",
                        to="room.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("is_autumn", models.BooleanField(default=False)),
                ("is_retreat_turn", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_float", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.location"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Units",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERD", "registered"),
                            ("INIT", "Formating the room database"),
                            ("WAIT", "Orders Incoming, Players Debating"),
                            ("RESOLVE", "Resolving Orders"),
                            ("RETREAT", "Orders Incoming, Only Players Retreating"),
                            ("UPDATE", "Update map with new Unit Positions"),
                            ("RESUPP", "Gaining Units After FALL"),
                            ("CHECK", "Check the closing conditions"),
                            (
                                "CLOSED",
                                "Will only change the status when room is closed",
                            ),
                        ],
                        default="INIT",
                        max_length=9,
                    ),
                ),
                ("close_time", models.DateTimeField(null=True)),
                (
                    "current_turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_turn",
                        to="room.turn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("is_alive", models.BooleanField(default=True)),
                ("is_finished", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="player_country",
                        to="room.country",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playr_joined_room",
                        to="room.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation",
                    models.CharField(
                        choices=[
                            ("MYBE", "Order Not Evaluated"),
                            ("MARK", "Order Marked for future Evaluation"),
                            ("NCVY", "Move Order has No Convoy"),
                            ("PASS", "Order Passed"),
                            ("VOID", "Order Failed"),
                            ("CUT", "Order Cut"),
                            ("BNCE", "Order Bounced with another"),
                            ("DLGE", "Order Unit Dislodged"),
                            ("DRPT", "Convoy Order Distrupted"),
                            ("DBAN", "Order Unit needs to Disband"),
                        ],
                        default="MYBE",
                        max_length=4,
                    ),
                ),
                (
                    "order_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="outcome_reference_to_order",
                        to="room.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Outcomes",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="reference_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reference_unit",
                to="room.unit",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reference_unit_current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reference_unit_current_location",
                to="room.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reference_unit_new_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reference_unit_new_location",
                to="room.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_oder",
                to="room.room",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="target_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="target_location",
                to="room.location",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="room.turn"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="target_unit",
                to="room.unit",
            ),
        ),
        migrations.CreateModel(
            name="Next_to",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Next_to_location",
                        to="room.location",
                    ),
                ),
                (
                    "next_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="next_to",
                        to="room.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Next_to",
            },
        ),
        migrations.CreateModel(
            name="Map_Polygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("polygon", models.CharField(max_length=500)),
                ("colour", models.CharField(max_length=10)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.location"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Map_Polygons",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.map"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.map"
            ),
        ),
    ]
