# Generated by Django 4.1.6 on 2023-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTERD", "registered"),
                    ("INITIALIZE", "initialize"),
                    ("WAIT", "Orders Incoming, Players Debating"),
                    ("RESOLVE", "Resolving Orders"),
                    ("RETREAT", "Orders Incoming, Only Players Retreating"),
                    ("UPDATE", "Update map with new Unit Positions"),
                    ("RESUPP", "Gaining Units After FALL"),
                    ("CHECK", "Check the closing conditions"),
                    ("CLOSED", "Will only change the status when room is closed"),
                ],
                default="REGISTERD",
                max_length=10,
            ),
        ),
    ]
