# Generated by Django 4.1.6 on 2023-05-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_order_target_location'),
        ('room', '0002_country_layer_alter_country_name_and_more'),
        ('room', '0002_remove_player_units_remove_room_players'),
    ]

    operations = [
    ]
