# Generated by Django 4.1.6 on 2023-05-03 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_merge_20230503_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_turn',
        ),
        migrations.RemoveField(
            model_name='country',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='country',
            name='player',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
