# Generated by Django 4.1.6 on 2023-05-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_remove_room_current_turn_remove_country_layer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=30)),
                (
                    "room_status",
                    models.CharField(
                        choices=[
                            ("Register", "registered"),
                            ("Init", "Initial"),
                            ("Wait", "Waiting"),
                            ("Check", "Checking"),
                            ("Retreat", "retreating "),
                            ("End", "Ending"),
                            ("Closed", "Closed"),
                        ],
                        default="Init",
                        max_length=8,
                    ),
                ),
                ("status", models.CharField(default="Open", max_length=6)),
                ("close_time", models.DateTimeField(null=True)),
                (
                    "current_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_turn",
                        to="room.turn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("is_alive", models.BooleanField(default=True)),
                ("is_finished", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="player_country",
                        to="room.country",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playr_joined_room",
                        to="room.room",
                    ),
                ),
            ],
        ),
    ]
