# Generated by Django 4.1.6 on 2023-05-05 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_room_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutcomeBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OutcomeBroadcast_outcome",
                        to="room.outcome",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OutcomeBroadcast_room",
                        to="room.room",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OutcomeBroadcast_turn",
                        to="room.turn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OrderBroadcast_order",
                        to="room.order",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OrderBroadcast_room",
                        to="room.room",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OrderBroadcast_turn",
                        to="room.turn",
                    ),
                ),
            ],
        ),
    ]
