# Generated by Django 4.1.6 on 2023-05-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0006_outcomebroadcast_orderbroadcast"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbroadcast",
            name="turn",
        ),
        migrations.RemoveField(
            model_name="outcomebroadcast",
            name="turn",
        ),
    ]
