# Generated by Django 4.1.6 on 2023-05-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0007_remove_orderbroadcast_turn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="target_unit",
            new_name="unit",
        ),
        migrations.RemoveField(
            model_name="order",
            name="current_location",
        ),
    ]
