# Generated by Django 4.1.6 on 2023-05-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0008_rename_target_unit_order_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="next_to",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Next_to_location",
                to="room.location",
            ),
        ),
    ]
