# Generated by Django 4.1.6 on 2023-05-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0009_alter_country_name_alter_next_to_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="text_pos",
            new_name="text_pos_x",
        ),
        migrations.AddField(
            model_name="location",
            name="text_pos_y",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
