# Generated by Django 4.1.6 on 2023-04-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0001_initial"),
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(default="", max_length=6)),
                (
                    "room_status",
                    models.CharField(
                        choices=[
                            ("Init", "Initial"),
                            ("Open", "Opening"),
                            ("Wait", "Waiting"),
                            ("Check", "Checking"),
                            ("End", "Ending"),
                            ("Closed", "Closed"),
                        ],
                        default="Init",
                        max_length=6,
                    ),
                ),
                (
                    "current_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="current_turn",
                        to="room.turn",
                    ),
                ),
                (
                    "hoster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hoster",
                        to="user.user",
                    ),
                ),
                ("players", models.ManyToManyField(to="user.user")),
            ],
            options={
                "verbose_name_plural": "Room",
            },
        ),
    ]
