# Generated by Django 4.1.6 on 2023-04-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_status",
                    models.CharField(
                        choices=[
                            ("Init", "Initial"),
                            ("Open", "Opening"),
                            ("Wait", "Waiting"),
                            ("Check", "Checking"),
                            ("End", "Ending"),
                            ("Closed", "Closed"),
                        ],
                        default="Init",
                        max_length=6,
                    ),
                ),
                (
                    "room_ID",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "hoster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hoster",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("players", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Room",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invitations",
                    models.ManyToManyField(related_name="invitations", to="host.room"),
                ),
                (
                    "joining_rooms",
                    models.ManyToManyField(
                        related_name="joining_rooms", to="host.room"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
