# Generated by Django 4.1.6 on 2023-04-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
        ("host", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="current_turn",
                to="room.turn",
            ),
        ),
    ]
