# Generated by Django 4.1.6 on 2023-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0002_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="id",
            field=models.IntegerField(null=True),
        ),
    ]
