# Generated by Django 4.1.6 on 2023-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0003_room_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="code",
            new_name="room_code",
        ),
        migrations.AlterField(
            model_name="room",
            name="room_status",
            field=models.CharField(
                choices=[
                    ("Init", "Initial"),
                    ("Open", "Opening"),
                    ("Wait", "Waiting"),
                    ("Check", "Checking"),
                    ("End", "Ending"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=6,
            ),
        ),
    ]
