# Generated by Django 4.1.6 on 2023-05-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0004_rename_code_room_room_code_alter_room_room_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Player",
        ),
    ]
