version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8001:8001"
    image: application:django
    container_name: django_room_container
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001