FROM node:lts-alpine

WORKDIR /
#home/runner/work/ESRS-diplomacy/ESRS-diplomacy/frontend/Diplomacy/

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080
CMD ["npm", "run", "server"]