name: Run Frontend (Vue.js) Tests
on:
  pull_request:
    branches: 'dev'
    types: [opened, synchronize]

jobs:
  test:
    name: Test the frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Change to frontend dir
        run:  cd frontend/Diplomacy
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run the tests
        run: |
          CI=true npm test:unit
        env:
          CI: true
